### ISSUE TITLE
[bug] data 出现 Invalid Date

### ISSUE THREAD

**Issue by Shunjun** [IronLu233/fileheader-pro#2]
同一个项目使用一段时间后 时间变成了 Invalid Date, 但是 lastModifyTime 是正常的 ，新建的项目也不会出现这个问题 

![image](https://user-images.githubusercontent.com/10445938/181679689-f0a0ae37-59dc-49ec-8d46-70f2b91d2cd1.png)

**Comment by IronLu233** [comment]
感谢您的反馈。
能否提供一下这个信息。
在git里执行下列命令
``` bash
git --no-pager log --format='%ai' --follow 你的文件路径
```
和
``` bash
git --no-pager log --format='%ai' --follow 你的文件路径
```
的输出呢
**请删掉输出中的邮件和作者信息脱敏**

**Comment by Shunjun** [comment]
可能是出问题的文件我 add 了，但是没有 commit.
打印的都没有时间

commit 之后需要删除之前的注释，重新添加才会正常显示时间

![截屏2022-08-01 09 06 25](https://user-images.githubusercontent.com/10445938/182054131-0fac1a1f-6881-4d87-95fd-84bfe7404cb6.png)

**Comment by IronLu233** [comment]
请尝试一下这个构建是否解决了您的问题呢
[fileheader-pro-1.3.2-alpha.zip](https://github.com/IronLu233/fileheader-pro/files/9239469/fileheader-pro-1.3.2-alpha.zip)

**Comment by Shunjun** [comment]
好像并没有,  暂存的文件手动创建一次注释就会 Invalid Date，有的文件是保存后自动被修改成了 Invalid Date
![屏幕录制2022-08-03 09 56 11](https://user-images.githubusercontent.com/10445938/182508348-94b06c39-3951-4f82-8874-6524c85b1ef1.gif)

**Comment by IronLu233** [comment]
好的，谢谢已经找到复现路径了。

**Comment by IronLu233** [comment]
[fileheader-pro-1.3.2-alpha-2.zip](https://github.com/IronLu233/fileheader-pro/files/9256377/fileheader-pro-1.3.2-alpha-2.zip)
请再试试这个？我这边add之后手动添加fileheader没有问题了

**Comment by Shunjun** [comment]
暂时好像没看出什么问题了~
感谢大佬
